export const CRAWL_SOURCE_QUEUE = Symbol('CRAWL_SOURCE_QUEUE');
export const FETCH_ARTICLE_QUEUE = Symbol('FETCH_ARTICLE_QUEUE');
export const PARSE_ARTICLE_QUEUE = Symbol('PARSE_ARTICLE_QUEUE');
export const EXTRACT_ARTICLE_QUEUE = Symbol('EXTRACT_ARTICLE_QUEUE');
export const CLUSTER_EVENT_QUEUE = Symbol('CLUSTER_EVENT_QUEUE');
export const SCORE_EVENT_QUEUE = Symbol('SCORE_EVENT_QUEUE');
