export enum ArticleStatus {
  DISCOVERED = 'DISCOVERED',
  FETCHING = 'FETCHING',
  FETCHED = 'FETCHED',
  PARSED = 'PARSED',
  EXTRACTING = 'EXTRACTING',
  EXTRACTED = 'EXTRACTED',
  IRRELEVANT = 'IRRELEVANT',
  DUPLICATE = 'DUPLICATE',
  FAILED = 'FAILED',
  ARCHIVED = 'ARCHIVED',
}

export enum EventStatus {
  NEW = 'NEW',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  VERIFIED = 'VERIFIED',
  CONFLICTED = 'CONFLICTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SELECTED = 'SELECTED',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
  MERGED = 'MERGED',
}

export enum OfficialStatus {
  OFFICIAL = 'OFFICIAL',
  CONFIRMED = 'CONFIRMED',
  RELIABLE_REPORT = 'RELIABLE_REPORT',
  MULTI_SOURCE_REPORT = 'MULTI_SOURCE_REPORT',
  UNVERIFIED = 'UNVERIFIED',
  RUMOR = 'RUMOR',
  DISPUTED = 'DISPUTED',
  FALSE = 'FALSE',
}

export enum NewsCategory {
  TRANSFER = 'TRANSFER',
  CONTRACT = 'CONTRACT',
  COACH_CHANGE = 'COACH_CHANGE',
  INJURY = 'INJURY',
  SUSPENSION = 'SUSPENSION',
  MATCH_RESULT = 'MATCH_RESULT',
  MATCH_PREVIEW = 'MATCH_PREVIEW',
  LEGAL = 'LEGAL',
  DISCIPLINARY = 'DISCIPLINARY',
  MANAGEMENT = 'MANAGEMENT',
  OWNERSHIP = 'OWNERSHIP',
  NATIONAL_TEAM = 'NATIONAL_TEAM',
  TACTICAL = 'TACTICAL',
  FINANCIAL = 'FINANCIAL',
  OFF_FIELD = 'OFF_FIELD',
  OTHER = 'OTHER',
}

export enum SourceType {
  OFFICIAL_CLUB = 'OFFICIAL_CLUB',
  OFFICIAL_LEAGUE = 'OFFICIAL_LEAGUE',
  OFFICIAL_FEDERATION = 'OFFICIAL_FEDERATION',
  NEWS_AGENCY = 'NEWS_AGENCY',
  TRUSTED_NEWSPAPER = 'TRUSTED_NEWSPAPER',
  TRANSFER_REPORTER = 'TRANSFER_REPORTER',
  LOCAL_SPORTS_MEDIA = 'LOCAL_SPORTS_MEDIA',
  AGGREGATOR = 'AGGREGATOR',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  UNTRUSTED_SOURCE = 'UNTRUSTED_SOURCE',
}

export enum EpisodeStatus {
  DRAFT = 'DRAFT',
  NEWS_SELECTED = 'NEWS_SELECTED',
  SCRIPT_GENERATING = 'SCRIPT_GENERATING',
  SCRIPT_READY = 'SCRIPT_READY',
  SCRIPT_REVIEWED = 'SCRIPT_REVIEWED',
  AUDIO_GENERATING = 'AUDIO_GENERATING',
  AUDIO_READY = 'AUDIO_READY',
  APPROVED = 'APPROVED',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
  FAILED = 'FAILED',
}

export enum CoverageScope {
  IRAN = 'IRAN',
  EUROPE = 'EUROPE',
  BOTH = 'BOTH',
  OTHER = 'OTHER',
}

/** Scheduled or manual intake batch for a Tehran editorial day */
export enum IntakeWaveStatus {
  SCHEDULED = 'SCHEDULED',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum WaveObservationType {
  NEW_EVENT = 'NEW_EVENT',
  NEW_SOURCE = 'NEW_SOURCE',
  NEW_DEVELOPMENT = 'NEW_DEVELOPMENT',
  OFFICIAL_CONFIRMATION = 'OFFICIAL_CONFIRMATION',
  CONFLICT_DETECTED = 'CONFLICT_DETECTED',
  SCORE_CHANGED = 'SCORE_CHANGED',
  NO_MEANINGFUL_CHANGE = 'NO_MEANINGFUL_CHANGE',
}

export enum DailyRundownStatus {
  COLLECTING = 'COLLECTING',
  EDITOR_REVIEW = 'EDITOR_REVIEW',
  PRE_FINAL = 'PRE_FINAL',
  LOCKED = 'LOCKED',
  SCRIPT_GENERATING = 'SCRIPT_GENERATING',
  SCRIPT_READY = 'SCRIPT_READY',
  FINALIZED = 'FINALIZED',
  REOPENED = 'REOPENED',
}

export enum RundownItemStatus {
  CANDIDATE = 'CANDIDATE',
  SHORTLISTED = 'SHORTLISTED',
  RESERVED = 'RESERVED',
  RECOMMENDED_FOR_REMOVAL = 'RECOMMENDED_FOR_REMOVAL',
  REMOVED = 'REMOVED',
  FINAL_SELECTED = 'FINAL_SELECTED',
}

/** How an item entered DailyRundown (ADR-007). */
export enum RundownItemAddedMode {
  MANUAL = 'MANUAL',
  AUTO = 'AUTO',
  SUGGESTED_ACCEPTED = 'SUGGESTED_ACCEPTED',
}

export enum RundownItemReviewStatus {
  PENDING_REVIEW = 'PENDING_REVIEW',
  ACCEPTED = 'ACCEPTED',
  DISMISSED = 'DISMISSED',
}

export enum AutomationDecisionType {
  HIGHLIGHT = 'HIGHLIGHT',
  SUGGEST_ADD = 'SUGGEST_ADD',
  SUGGEST_REPLACE = 'SUGGEST_REPLACE',
  AUTO_ADD = 'AUTO_ADD',
  HOLD = 'HOLD',
}

export enum RundownSection {
  LEAD = 'LEAD',
  MAIN = 'MAIN',
  BRIEF = 'BRIEF',
  RESULTS = 'RESULTS',
  WATCHLIST = 'WATCHLIST',
}

export enum CoverageDimension {
  SCOPE = 'SCOPE',
  CATEGORY = 'CATEGORY',
  ENTITY = 'ENTITY',
  SECTION = 'SECTION',
}

export enum CoverageEnforcement {
  HARD = 'HARD',
  SOFT = 'SOFT',
  ADVISORY = 'ADVISORY',
}

export enum CoverageBucketStatus {
  NO_AVAILABLE_NEWS = 'NO_AVAILABLE_NEWS',
  AVAILABLE_NOT_SELECTED = 'AVAILABLE_NOT_SELECTED',
  UNDER_TARGET = 'UNDER_TARGET',
  ON_TARGET = 'ON_TARGET',
  OVER_TARGET = 'OVER_TARGET',
  NO_TARGET = 'NO_TARGET',
}

export enum CoverageRecommendationType {
  COVERAGE_GAP = 'COVERAGE_GAP',
  NO_AVAILABLE_NEWS = 'NO_AVAILABLE_NEWS',
  OVER_COVERED = 'OVER_COVERED',
  TEAM_REDUNDANCY = 'TEAM_REDUNDANCY',
  CATEGORY_REDUNDANCY = 'CATEGORY_REDUNDANCY',
  REPLACEMENT_SUGGESTION = 'REPLACEMENT_SUGGESTION',
}

export enum CoverageDimensionKey {
  SCOPE = 'SCOPE',
  TEAM = 'TEAM',
  COMPETITION = 'COMPETITION',
  CATEGORY = 'CATEGORY',
  TRACKED_EVENT = 'TRACKED_EVENT',
}

export enum FeedType {
  RSS = 'rss',
  SITEMAP = 'sitemap',
  LIST = 'list',
}

export enum HealthStatus {
  HEALTHY = 'healthy',
  DEGRADED = 'degraded',
  DOWN = 'down',
  UNKNOWN = 'unknown',
}

export enum CrawlRunStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  SUCCESS = 'SUCCESS',
  PARTIAL = 'PARTIAL',
  FAILED = 'FAILED',
}

export enum CrawlTrigger {
  SCHEDULE = 'schedule',
  MANUAL = 'manual',
  RETRY = 'retry',
}

export enum SystemRole {
  SYSTEM_ADMIN = 'system_admin',
  EDITOR = 'editor',
  REPORTER = 'reporter',
  CONTENT_MANAGER = 'content_manager',
}

export const QUEUE_NAMES = [
  'crawl-source',
  'fetch-article',
  'parse-article',
  'extract-article',
  'generate-embedding',
  'detect-duplicate',
  'cluster-event',
  'score-event',
  'verify-event',
  'generate-podcast',
  'fact-check-script',
  'generate-audio',
  'publish-episode',
  'send-notification',
  'cleanup',
] as const;

export type QueueName = (typeof QUEUE_NAMES)[number];
